source :rubygems
source "http://rubygems.org"

source :rubyforge
source "http://gems.rubyforge.org"

source :gemcutter
source "http://gemcutter.org"

gem 'compass'
gem 'haml'
gem 'coffee-script'
gem 'coffee-filter'
gem 'hpricot'
