source "http://rubygems.org"
#source "http://gems.rubyforge.org"
#source "http://gemcutter.org"

gem 'compass'
gem 'haml'
gem 'coffee-script'
gem 'hpricot'
gem 'guard'

# rbenv
gem 'rbenv-rehash'

# homebrew
gem 'brewdler'
