" Removing scrollbars
set guitablabel=%-0.12t%M
set guioptions-=T
set guioptions-=r
set guioptions-=L
set guioptions+=a
set guioptions+=m
if has('win32') || has('win64')
	"" TODO
	set guifont=Osaka−等幅:h11:cSHIFTJIS
else
	set listchars=tab:▸\ ,eol:¬,nbsp:%
endif
set visualbell t_vb=
colorscheme evening
