se nobackup

" Removing scrollbars
se guitablabel=%-0.12t%M
se guioptions-=T
se guioptions-=r
se guioptions-=L
se guioptions+=a
se guioptions+=m
se clipboard+=autoselect
se clipboard+=unnamed
if has('win32') || has('win64')
	"" TODO
	se guifont=Osaka−等幅:h11:cSHIFTJIS
else
	se listchars=tab:▸\ ,eol:¬,nbsp:%
endif
se visualbell t_vb=
colorscheme evening
