# ref: http://masutaka.net/chalow/2014-01-25-1.html

# update Homebrew
update

# Add Repository
tap homebrew/binary
tap phinze/homebrew-cask

install ack
install the_silver_searcher

install android-sdk

install gnu-getopt
install gnu-tar
install discount
install graphicsmagick
install jq
install mobile-shell
install lv
install nkf
install protobuf
install pidof
install htop-osx
install pstree
install tree
install wget

install node
install casperjs
install phantomjs

install plenv
install perl-build
install rbenv
install ruby-build
install pyenv
install lua

install vim
install macvim

install tmux
install reattach-to-user-namespace

install sip
install sshfs

# vcs
install subversion
install git
install git-flow
install hub
install tig
install mercurial

install zsh
install zsh-completions

#install memcached
#install mongodb
#install redis
#install sqlite

install brew-cask
#cask install appcleaner
#cask install dropbox
#cask install firefox
#cask install google-chrome
#cask install handbrake
#cask install libreoffice
#cask install limechat
#cask install openoffice
#cask install opera
#cask install sequel-pro
#cask install skitch
#cask install skype
#cask install sublime-text
#cask install vagrant
#cask install virtualbox
