# Set up the prompt

autoload -Uz promptinit
promptinit

setopt histignorealldups sharehistory histreduceblanks histignorespace

# Use emacs keybindings even if our EDITOR is set to vi
bindkey -e

# Keep 10000 lines of history within the shell and save it to ~/.zsh_history:
HISTSIZE=10000
SAVEHIST=10000
HISTFILE="${XDG_DATA_HOME}/zsh/zsh_history"

# zinit
ZINIT_HOME="${XDG_DATA_HOME}/zinit/zinit.git"
if [ ! -d "${ZINIT_HOME}" ]; then
  mkdir -p "$(dirname $ZINIT_HOME)"
  git clone https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME"
fi
source "${ZINIT_HOME}/zinit.zsh"

# Use modern completion system
autoload -Uz compinit
compinit

export LANG="ja_JP.UTF-8"
export LC_ALL=$LANG
export PATH=$HOME/bin:/opt/homebrew/bin:$PATH
export EDITOR=$(which nvim 2>/dev/null || which vim)

autoload history-search-end
zle -N history-beginning-search-backward-end history-search-end
zle -N history-beginning-search-forward-end history-search-end
bindkey "^p" history-beginning-search-backward-end
bindkey "^n" history-beginning-search-forward-end

. $ZDOTDIR/functions.zsh

source_if_exists "$ZDOTDIR/zinit.zsh"

zle -N zle_search_history
zle -N zle_search_git_repos
zle -N zle_search_git_branch
zle -N zle_checkout_github_pr
bindkey -r "^R"
bindkey "^R" zle_search_history
bindkey "^G^G" zle_search_git_repos
bindkey "^G^B" zle_search_git_branch
bindkey "^G^P" zle_checkout_github_pr

export ASDF_CONFIG_FILE="${XDG_CONFIG_HOME}/asdf/asdfrc"

## load user .zshrc configuration file
source_if_exists $ZDOTDIR/aliases.zsh
source_if_exists $ZDOTDIR/.zshrc.local
