# Set up the prompt

autoload -Uz promptinit
promptinit

setopt histignorealldups sharehistory histreduceblanks histignorespace

# Use emacs keybindings even if our EDITOR is set to vi
bindkey -e

# Keep 1000 lines of history within the shell and save it to ~/.zsh_history:
HISTSIZE=10000
SAVEHIST=10000
HISTFILE=$HOME/.zsh_history

# Use modern completion system
autoload -Uz compinit
compinit

export LANG="ja_JP.UTF-8"
export LC_ALL=$LANG
export EDITOR=$(which vim)
export PATH=$HOME/bin:$PATH

autoload history-search-end
zle -N history-beginning-search-backward-end history-search-end
zle -N history-beginning-search-forward-end history-search-end
bindkey "^p" history-beginning-search-backward-end
bindkey "^n" history-beginning-search-forward-end

. $HOME/.zsh_functions

source_if_exists "$HOME/.zshrc.zplug"

export ANYENV_ROOT=$HOME/.anyenv
exists "$ANYENV_ROOT/bin"        && export PATH=$ANYENV_ROOT/bin:$PATH
exists "$ANYENV_ROOT/bin/anyenv" && eval "$(anyenv init -)"

## load user .zshrc configuration file
source_if_exists $HOME/.aliases
source_if_exists $HOME/.zshrc.local
source_if_exists $HOME/.zshrc.peco
